### ISSUE TITLE
Docs/ churning on `yarn`

### ISSUE THREAD

**Issue by EthanJStark** [kofile/react-components#6]
### Reproduction steps: 
`yarn`
`git status` yields
```
	modified:   docs/index.html
	modified:   docs/loader/main.js
	modified:   docs/loader/main.js.map
```
`git diff` yields changed local filepaths like:

```js
-  <script> mountPlayground({"loaderUri":"./loader/index.html","projectKey":"/Users/evan/Code/kofile/react-components","webpackConfigType":"default"}); </script>
+  <script> mountPlayground({"loaderUri":"./loader/index.html","projectKey":"/Users/estark/workspace/react-components","webpackConfigType":"default"}); </script>
```

If these are being regenerated for each user when they run `yarn`, I wonder if a `.gitignore` is in order?

CC @neezer

**Comment by EthanJStark** [comment]
Didn't see anything about this behavior in the Cosmos docs or issues.

**Comment by neezer** [comment]
This is already being tracked: see https://github.com/kofile/react-components/pull/2#pullrequestreview-104099684

**Comment by EthanJStark** [comment]
Nice!
